name: Template-tests
on: push
jobs:
    Template-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ./committime_template 
              with: 
                  app: "GitHub-Deploy-test"
                  url: http://webhook-exporter-pelorus.apps.grey.dev.iad2.dc.paas.redhat.com/pelorus/webhook
            - uses: ./deploytime_template
              with: 
                  app: "GitHub-Commit-test"
                  url: http://webhook-exporter-pelorus.apps.grey.dev.iad2.dc.paas.redhat.com/pelorus/webhook